version: '3'

services:
  php:
    container_name: multi-tenant-php
    build: ./docker
    tty: true
    volumes:
      - ./:/var/www/html
      - /var/www/html/node_modules
      - /var/www/html/vendor
    networks:
     - multi-tenant

  nginx:
    container_name: multi-tenant-nginx
    image: nginx:stable-alpine
    ports:
      - "8180:80"
    depends_on:
      - php
      - mysql
    volumes:
      - ./:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - /var/www/html/node_modules
      - /var/www/html/vendor
    networks:
      - multi-tenant

  mysql:
    container_name: multi-tenant-mysql
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: top_secret
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    restart: unless-stopped
    tty: true
    ports:
      - "3606:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - multi-tenant

  npm:
    container_name: multi-tenant-npm
    image: node:13.7-alpine
    entrypoint: [ "npm" ]
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    networks:
      - multi-tenant

networks:
  multi-tenant:
    driver: bridge